#PGM API: By Ilario42: www.ilariochiera.it/documentations/pgmapi
#Send me a message on telegram @Ilario42 :)
Server: "PGM-1"

Stats:
    Kills: 1
    Death: 1

Coins:
    Kills: 5
    Death: 3

MySQL:  
    Host: localhost
    Port: 3306
    DbName: pgmapi
    Username: root
    Password: ''  